version: '3.8'

services:
  reacter:
    build: .
    container_name: reacter
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      # Persist database and logs
      - ./data:/app/data
      - ./logs:/app/logs
      # Mount .env file if it exists
      - ./.env:/app/.env:ro
    # Optional: Add healthcheck
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/bot_data.db').close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M